name: Matrix based

on:
  workflow_dispatch: 
    inputs:
      dev:
        default: false
        type: boolean
        description: 'Deploy to dev'
      test:
        default: false
        type: boolean
        description: 'Deploy to test'
      stage:
        default: false
        type: boolean
        description: 'Deploy to stage'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ toJson(contains(github.event.inputs.dev, 'true') && 'dev' || '') }}
             ${{ toJson(contains(github.event.inputs.test, 'true') && 'test' || '') }}
             ${{ toJson(contains(github.event.inputs.stage, 'true') && 'stage' || '') }}
    steps:
      - name: Run the build
        run: |
          echo "Running for environment: ${{ matrix.env }}"
