name: Matrix based

on:
  workflow_dispatch: 
    inputs:
      dev:
        default: false
        type: boolean
        description: 'Deploy to dev'
      test:
        default: false
        type: boolean
        description: 'Deploy to test'
      stage:
        default: false
        type: boolean
        description: 'Deploy to stage'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ fromJSON('["dev", "test", "stage"]') 
          | map(e => (github.event.inputs[e] == 'true') && e) 
          | filter(e => e) }}
    steps:
      - name: Run the build
        run: |
          echo "Running for environment: ${{ matrix.env }}"
