name: Matrix based

on:
  workflow_dispatch: 
    inputs:
      dev:
        default: false
        type: boolean
        description: 'Deploy to dev'
      test:
        default: false
        type: boolean
        description: 'Deploy to test'
      stage:
        default: false
        type: boolean
        description: 'Deploy to stage'
jobs:
  build:
    strategy:
      matrix:
        env: [dev, test, stage]
    runs-on: ubuntu-latest
    steps:
      - name: Run the build
        run: |
          echo ${{matrix.env}}
