name: Matrix based

on:
  workflow_dispatch: 
    inputs:
      dev:
        default: false
        type: boolean
        description: 'Deploy to dev'
      test:
        default: false
        type: boolean
        description: 'Deploy to test'
      stage:
        default: false
        type: boolean
        description: 'Deploy to stage'

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set dynamic matrix
        id: set-matrix
        run: |
          MATRIX=()
          if [ "${{ github.event.inputs.dev }}" == "true" ]; then MATRIX+=('"dev"'); fi
          if [ "${{ github.event.inputs.test }}" == "true" ]; then MATRIX+=('"test"'); fi
          if [ "${{ github.event.inputs.stage }}" == "true" ]; then MATRIX+=('"stage"'); fi
          echo "matrix=[${MATRIX[*]}]" >> $GITHUB_ENV
        shell: bash

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
    steps:
      - name: Run the build
        run: |
          echo "Running for environment: ${{ matrix.env }}"
