name: Matrix based

on:
  workflow_dispatch: 
    inputs:
      dev:
        default: false
        type: boolean
        description: 'Deploy to dev'
      test:
        default: false
        type: boolean
        description: 'Deploy to test'
      stage:
        default: false
        type: boolean
        description: 'Deploy to stage'

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      env_matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set Matrix
        id: set-matrix
        run: |
          MATRIX=()
          if [ "${{ github.event.inputs.dev }}" == "true" ]; then
            MATRIX+=dev
          fi
          if [ "${{ github.event.inputs.test }}" == "true" ]; then
            MATRIX+=test
          fi
          if [ "${{ github.event.inputs.stage }}" == "true" ]; then
            MATRIX+=stage
          fi
          echo "Matrix environments: ${MATRIX[@]}"
          echo "matrix=$(jq -c -n --argjson arr "$(printf '%s\n' "${MATRIX[@]}" | jq -R . | jq -s .)" '{"env": $arr}')" >> "$GITHUB_OUTPUT"

  build:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.env_matrix) }}
    steps:
      - name: Run the build
        run: |
          echo "Running for environment: ${{ matrix.env }}"
